include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-linux.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-freebsd.yml
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-extragear-windows.yml

stages:
    - build

before_script:
  - git clone --depth=1 https://cgit.kde.org/pulseaudio-qt.git /build/ci-tooling

kdeconnect-kde_xenial_click:
    stage: build  
    image: clickable/ci-16.04-armhf
    script:
        - clickable clean build click-build 
    artifacts:
        paths:
            - build/*.click
        expire_in: 1 week
